import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NewsLetter from "./components/NewsLetter Banner Section/NewsLetter";
import Navbar from "./components/Navbar Section/Navbar";
import Footer from "./components/Footer Section copy/Footer";
import ContactUs from "./components/Contact Us Section/ContactUs";
import Testimonials from "./components/Testimonials Section/Testimonials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NewsLetter/>
        <Navbar/>
        {children}
        <Testimonials/>
        <ContactUs/>
        <Footer/>
      </body>
    </html>
  );
}
